import { z } from 'zod'

const supportedModifierKey = z.enum(['Alt', 'AltGr', 'AltRight', 'Control', 'Meta', 'Super', 'CommandOrCtrl'])

const supportedShortcutKey = z.enum([
  'Comma',
  'Period',
  'Forwardslash',
  'Slash',
  'Tab',
  'Space',
  'Enter',
  'Escape',
  'ArrowUp',
  'ArrowDown',
  'ArrowLeft',
  'ArrowRight',
  'F1',
  'F2',
  'F3',
  'F4',
  'F5',
  'F6',
  'F7',
  'F8',
  'F9',
  'F10',
  'F11',
  'Digit9',
  'Digit8',
  'Digit7',
  'Digit6',
  'Digit5',
  'Digit4',
  'Digit3',
  'Digit2',
  'Digit1',
  'Digit0',
  'KeyA',
  'KeyB',
  'KeyC',
  'KeyD',
  'KeyE',
  'KeyF',
  'KeyG',
  'KeyH',
  'KeyI',
  'KeyJ',
  'KeyK',
  'KeyL',
  'KeyM',
  'KeyN',
  'KeyO',
  'KeyP',
  'KeyQ',
  'KeyR',
  'KeyS',
  'KeyT',
  'KeyU',
  'KeyV',
  'KeyW',
  'KeyX',
  'KeyY',
  'KeyZ',
  'NumpadDivide',
  'NumpadMultiply',
  'NumpadSubtract',
  'NumpadAdd',
  'NumpadDecimal',
  'Numpad9',
  'Numpad8',
  'Numpad7',
  'Numpad6',
  'Numpad5',
  'Numpad4',
  'Numpad3',
  'Numpad2',
  'Numpad1',
  'Numpad0'
])

export const ShortcutSchema = z.object({
  modifierKeys: z.array(supportedModifierKey).default([]),
  shortcutKey: supportedShortcutKey,
  enabled: z.boolean().default(true),
  configuring: z.boolean().default(false),
  nonUSLayout: z.boolean().default(false)
})

export type ModifierKey = z.infer<typeof supportedModifierKey>
export type ShortcutKey = z.infer<typeof supportedShortcutKey>
export type Shortcut = z.infer<typeof ShortcutSchema>
