name: Build installer artifacts

on:
  push:
    branches:
      - 'build-workflow'

env:
 GH_TOKEN: ${{ secrets.GH_RELEASE_DEPLOYMENT_TOKEN }}

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
        cache: 'npm'
    - run: npm run setup
    - run: npm run compile
    - run: npm run test:unit
    - run: npm run bundle
    - run: sleep 4 # sleep for 4 seconds before publishing
    # - run: npm run release

  build_windows:
    runs-on: windows-latest

    env:
      CSC_LINK: ${{ secrets.WINDOWS_CSC_CERTIFICATE }}
      CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CSC_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
        cache: 'npm'
    - run: npm run setup
    - run: npm run compile
    - run: npm run test:unit
    - run: npm run bundle
    - run: Start-Sleep -s 4 # sleep for 4 seconds before publishing
    # - run: npm run release

  build-mac:
    runs-on: macos-11
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
        cache: 'npm'
    - run: npm run setup
    - run: npm run compile
    - run: npm run test:unit
    - run: npm run bundle
    - run: sleep 4 # sleep for 4 seconds before publishing
    # - run: npm run release
