name: Build and publish installer artifacts for all platforms

on:
  push:
    branches:
      - '0.5'

env:
 GH_TOKEN: ${{ secrets.GH_RELEASE_DEPLOYMENT_TOKEN }}

jobs:
  build_release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        include:
          - os: macos-11
            cert_key: APPLE_DEVELOPER_SIGNING_CERTIFICATE
            cert_password_key: APPLE_CERTIFICATE_PASSWORD
            apple_id_key: APPLE_ID
            apple_id_password_key: APPLE_ID_PASSWORD
          - os: windows-latest
            cert_key: WINDOWS_CSC_CERTIFICATE
            cert_password_key: WINDOWS_CSC_PASSWORD

    runs-on: ${{ matrix.os }}

    env:
      CSC_LINK: ${{ secrets[matrix.cert_key] }}
      CSC_KEY_PASSWORD: ${{ secrets[matrix.cert_password_key] }}
      APPLE_ID: ${{ secrets[matrix.apple_id_key] }}
      APPLE_ID_PASSWORD: ${{ secrets[matrix.apple_id_password_key] }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
          cache: 'npm'
      - name: install Linux dev tools
        if: ${{ matrix.os }} == ubuntu-latest
        run: sudo apt install -y libudev-dev
      - name: create NPM config file
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ./.npmrc
      - run: npm run setup
      - run: npm run compile
      - run: npm run test:main
      - run: npm run test:components
      - run: npm run bundle
      - name: Sleep for 4 seconds
        shell: bash
        run: sleep 4
      - run: npm run publish
