name: Build installer artifacts

on:
  workflow_call:
    branches:
      - 'build-workflow'

# env:
#  GH_TOKEN: ${{ secrets.GITHUB_DEPLOYMENT_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
        cache: 'npm'
    - run: echo "hello, world!"
