name: Build and publish installer artifacts for all platforms

on:
  push:
    branches:
      - '0.5'
      - 'test-publish'

env:
 GH_TOKEN: ${{ secrets.GH_RELEASE_DEPLOYMENT_TOKEN }}

jobs:
  create_draft_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: read version from package.json
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: check for existing release
      run: gh release list --exclude-drafts | grep -e ".*v${{ steps.package-version.outputs.current-version }}" && exit 1
