name: Build installer artifacts

on:
  push:
    branches:
      - 'build-workflow'

env:
 GH_TOKEN: ${{ secrets.GITHUB_DEPLOYMENT_TOKEN }}

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
        cache: 'npm'
    - run: npm run setup
    - run: npm run compile
    - run: npm run test:unit

  build_windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.4.0
        cache: 'npm'
    - run: npm run setup
    - run: npm run compile
    - run: npm run test:unit
