name: Update application version after release has been published

on:
  release:
    types: [published]

jobs:
  bump_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Update version
        id: update-version
        run: sh scripts/update-version.sh
      - name: Commit & Push new version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "chore: update version"
          git push
