name: Clear old release and create a new one

on:
  push:
    branches:
      - 'auto-release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: create new draft release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GH_RELEASE_DEPLOYMENT_TOKEN }}
        automatic_release_tag: v0.5.0-beta14xz
        prerelease: true
        draft: true
        title: 0.5.0-beta14xz
